server:
  port: 8401

spring:
  application:
    name: clouldalibaba-sentinel-service
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.56.103:1111
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
      datasource:
        ds1:
          nacos:
            server-addr: 192.168.56.103:1111
            dataId: cloudalibaba-sentinel-service
            groupId: DEFAULT_GROUP
            data-type: json
            rule-type: flow

management:
  endpoints:
    web:
      exposure:
        include: '*'